apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .Values.Name }}
type: Opaque
stringData:
  SERVICE_BACKEND_HOST:        {{ .Values.services.frontend.environment.SERVICE_BACKEND_HOST }}
  SERVICE_BACKEND_PORT:        {{ .Values.services.frontend.environment.SERVICE_BACKEND_PORT | quote }}
