{{- $env := index .Values "services" "bg-tasks" "env" -}}

{{- if eq $env "dev" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      service: {{ .Values.Name }}
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        service: {{ .Values.Name }}
    spec:
      terminationGracePeriodSeconds: 15
      volumes:
      - name: business
        hostPath:
          path: /src/plasticine/backend/business
          type: Directory
      - name: data-layer
        hostPath:
          path: /src/plasticine/backend/data-layer
          type: Directory
      - name: microservices
        hostPath:
          path: /src/plasticine/backend/microservices
          type: Directory
      - name: presentation
        hostPath:
          path: /src/plasticine/backend/presentation
          type: Directory
      - name: scripts
        hostPath:
          path: /src/plasticine/backend/scripts
          type: Directory
      containers:
        - name: {{ .Values.Name }}
          image: plasticine/backend:dev
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: business
            mountPath: /src/plasticine/backend/business
          - name: data-layer
            mountPath: /src/plasticine/backend/data-layer
          - name: microservices
            mountPath: /src/plasticine/backend/microservices
          - name: presentation
            mountPath: /src/plasticine/backend/presentation
          - name: scripts
            mountPath: /src/plasticine/backend/scripts
          envFrom:
          - secretRef:
             name: secret-{{ .Values.Name }}
          command: [ "yarn", "run", "background-tasks:start" ]

{{- end }}

{{- if eq $env "prod" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.Name }}
spec:
  strategy:
    type: Recreate
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      service: {{ .Values.Name }}
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        service: {{ .Values.Name }}
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: {{ .Values.Name }}
          image: plasticine/backend
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
             name: secret-{{ .Values.Name }}
          command: [ "yarn", "run", "background-tasks:start:production" ]

{{- end }}