export default {
  name: 'Log',
  plural: 'Logs',
  alias: 'log',
  type: 'core',
  template: 'base',
  access_script: 'p.currentUser.canAtLeastRead()',
  order: '-100',
  __lock: ['delete'],
  fields: [
    {
      name: 'UUID',
      alias: 'uuid',
      type: 'string',
      options: { length: 20 },
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Domain',
      alias: 'domain',
      type: 'string',
      index: 'simple',
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Level',
      alias: 'level',
      type: 'array_string',
      index: 'simple',
      options: { values: { info: 'Info', error: 'Error' }, length: 2048 },
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Trigger type',
      alias: 'trigger_type',
      type: 'string',
      index: 'simple',
      __lock: ['delete'],
    },
    {
      name: 'Trigger ID',
      alias: 'trigger_id',
      type: 'integer',
      __lock: ['delete'],
    },
    {
      name: 'Target model',
      alias: 'target_model',
      type: 'reference',
      options: { foreign_model: 'model', foreign_label: 'name' },
      hidden_when_script: "!p.record.getValue('target_model')",
      __lock: ['delete'],
    },
    {
      name: 'Target record',
      alias: 'target_record',
      type: 'integer',
      hidden_when_script: "!p.record.getValue('target_record')",
      __lock: ['delete'],
    },
    {
      name: 'Message',
      alias: 'message',
      type: 'string',
      options: { length: 100000 },
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Meta',
      alias: 'meta',
      type: 'string',
      options: { length: 100000, syntax_hl: 'js' },
      __lock: ['delete'],
    },
    {
      name: 'Timestamp',
      alias: 'timestamp',
      type: 'integer',
      required_when_script: 'false',
      __lock: ['delete'],
    },
    {
      name: 'Tag',
      alias: 'tag',
      type: 'string',
      __lock: ['delete'],
    },
    {
      name: 'Duration',
      alias: 'duration',
      type: 'integer',
      __lock: ['delete'],
    },
  ],
  views: [
    {
      name: 'Default',
      alias: 'default',
      type: 'grid',
      condition_script: 'p.currentUser.isAdmin()',
      layout: 'Default',
      filter: 'Default',
      order: 400,
      __lock: ['delete'],
    },
    {
      name: 'MC proxy',
      alias: 'mc_proxy',
      appearance:'Coloring',
      type: 'grid',
      condition_script: 'p.currentUser.isAdmin()',
      layout: 'Default',
      filter: 'Mc proxy',
      order: 350,
      __lock: ['delete'],
    },
    {
      name: 'BG: Tasks',
      alias: 'background_tasks',
      type: 'grid',
      condition_script: 'p.currentUser.isAdmin()',
      layout: 'Default',
      filter: 'BG: Tasks',
      order: 300,
      __lock: ['delete'],
    },
    {
      name: 'BG: Mails',
      alias: 'background_mails',
      type: 'grid',
      condition_script: 'p.currentUser.isAdmin()',
      layout: 'Default',
      filter: 'BG: Mails',
      order: 200,
      __lock: ['delete'],
    },
    {
      name: 'BG: All',
      alias: 'background_all',
      type: 'grid',
      condition_script: 'p.currentUser.isAdmin()',
      layout: 'Default',
      filter: 'BG: All',
      order: 100,
      __lock: ['delete'],
    },
    {
      name: 'Web',
      alias: 'web',
      type: 'grid',
      condition_script: 'p.currentUser.isAdmin()',
      layout: 'Default',
      filter: 'Web',
      order: 0,
      __lock: ['delete'],
    },
  ],
  layouts: [
    {
      name: 'Default',
      type: 'grid',
      options: {
        columns: ['timestamp', 'tag', 'level', 'message', 'created_at', 'created_by'],
        columns_options: {},
        sort_order: [
          { field: 'timestamp', type: 'descending' },
          { field: 'tag', type: 'none' },
          { field: 'level', type: 'none' },
          { field: 'message', type: 'none' },
          { field: 'created_at', type: 'none' },
          { field: 'created_by', type: 'none' },
        ],
        wrap_text: true,
        no_wrap_text_limit: 50,
      },
      __lock: ['delete'],
    },
  ],
  forms: [
    {
      name: 'Default',
      alias: 'default',
      order: 0,
      active: true,
      condition_script: 'true',
      options: {
        components: {
          list: [
            '__tab__.main',
            '__section__.1',
            '__column__.1_1',
            'level',
            '__column__.1_2',
            'domain',
            '__section__.2',
            'message',
            'meta',
            '__section__.3',
            '__column__.3_1',
            'trigger_id',
            'trigger_type',
            'duration',
            '__column__.3_2',
            'target_model',
            'target_record',
            'uuid',
            'tag',
            '__tab__.service',
            '__section__.4',
            'id',
            '__section__.5',
            '__column__.5_1',
            'created_at',
            'updated_at',
            '__column__.5_2',
            'created_by',
            'updated_by',
          ],
          options: {
            '__tab__.main': { expanded: true, name: 'Main' },
            '__tab__.service': { name: 'Service' },
          },
        },
        related_components: { list: [], options: {} },
      },
      __lock: ['delete'],
    },
  ],
  filters: [
    {
      name: 'Web',
      query: "`domain` = 'web'",
    },
    {
      name:'Mc proxy',
      query:'`domain` = \'mc_proxy\''
    },
    {
      name: 'BG: Tasks',
      query: "`domain` = 'background_tasks'",
    },
    {
      name: 'BG: Mails',
      query: "`domain` = 'background_mails'",
    },
    {
      name: 'BG: All',
      query: "`domain` like '%background%'",
    },
  ],
  permissions: [
    { type: 'model', action: 'create', script: 'p.currentUser.canAtLeastWrite()', __lock: ['delete'] },
    { type: 'model', action: 'update', script: 'false', __lock: ['delete'] },
    { type: 'model', action: 'delete', script: 'false', __lock: ['delete'] },
  ],

  privileges: [
    { level: 'read_write', owner_type: 'all_users', __lock: ['delete'] },
  ],
};
