export default {
  name: '[MC] Device',
  plural: '[MC] Devices',
  alias: 'mc_device',
  type: 'core',
  template: 'base',
  access_script: 'p.currentUser.canAtLeastRead()',
  order: '-100',
  __lock: ['delete'],
  fields: [
    {
      name: 'Device Name',
      alias: 'device_name',
      type: 'string',
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Model',
      alias: 'model',
      type: 'string',
      readonly_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Device ID',
      alias: 'device_id',
      type: 'string',
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'State',
      alias: 'state',
      type: 'array_string',
      options: {
        values: {
          new: 'New',
          active: 'Active', // todo был статус approved прогнать миграции
          blocked: 'Blocked',
        },
        default: 'active'
      },
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Operating system',
      alias: 'operating_system',
      type: 'string',
      readonly_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Version changed on',
      alias: 'version_changed_on',
      type: 'datetime',
      readonly_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'MC version',
      alias: 'mc_version',
      type: 'string',
      readonly_when_script: 'true',
      __lock: ['delete'],
    },
  ],
  views: [
    {
      name: 'Default',
      alias: 'default',
      type: 'grid',
      condition_script: 'p.currentUser.isAdmin()',
      layout: 'Default',
      filter: 'Default',
      __lock: ['delete'],
    },
  ],
  layouts: [
    {
      name: 'Default',
      type: 'grid',
      options: {
        columns: ['id', 'device_id', 'device_name', 'model', 'state', 'created_at', 'updated_at'],
        columns_options: {},
        sort_order: [
          { field: 'id', type: 'descending' },
          { field: 'name', type: 'none' },
          { field: 'number', type: 'none' },
          { field: 'status', type: 'none' },
          { field: 'created_at', type: 'none' },
          { field: 'updated_at', type: 'none' },
          { field: 'created_by', type: 'none' },
          { field: 'updated_by', type: 'none' },
        ],
        wrap_text: true,
        no_wrap_text_limit: 50,
      },
      __lock: ['delete'],
    },
  ],
  forms: [
    {
      name: 'Default',
      alias: 'default',
      order: 0,
      active: true,
      condition_script: 'true',
      options: {
        components: {
          list: [
            '__tab__.main',
            '__section__.1',
            '__column__.1_1',
            'device_id',
            'device_name',
            'model',
            'state',
            '__column__.1_2',
            'operating_system',
            'version_changed_on',
            'mc_version',
            '__tab__.service',
            '__section__.2',
            'id',
            '__section__.3',
            '__column__.3_1',
            'created_at',
            'updated_at',
            '__column__.3_2',
            'created_by',
            'updated_by',
          ],
          options: {
            '__tab__.main': { expanded: true, name: 'Main' },
            '__tab__.service': { name: 'Service' },
          },
        },
        related_components: { list: [], options: {} },
      },
      __lock: ['delete'],
    },
  ],
  permissions: [
    { type: 'model', action: 'create', script: 'p.currentUser.isAdmin()', __lock: ['delete'] },
    { type: 'model', action: 'update', script: 'p.currentUser.isAdmin()', __lock: ['delete'] },
    { type: 'model', action: 'delete', script: 'p.currentUser.isAdmin()', __lock: ['delete'] },
  ],
};
