export default {
  name: 'TCross',
  plural: 'TCrosses',
  alias: 't_cross',
  type: 'core',
  template: 'base',
  access_script: 'p.currentUser.canAtLeastRead()',
  order: '-100',
  audit: 'none',
  __lock: ['delete'],
  fields: [
    {
      name: 'DTF field',
      alias: 'dtf_field_id',
      type: 'reference',
      options: {
        foreign_model: 'field',
        foreign_label: 'name',
      },
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'DTF record',
      alias: 'dtf_record_id',
      type: 'integer',
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Data model',
      alias: 'data_model_id',
      type: 'reference',
      options: {
        foreign_model: 'model',
        foreign_label: 'name',
        view: 'template',
      },
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Data record',
      alias: 'data_record_id',
      type: 'integer',
      __lock: ['delete'],
    },
    {
      name: 'DVF field',
      alias: 'dvf_field_id',
      type: 'reference',
      options: {
        foreign_model: 'field',
        foreign_label: 'name',
      },
      __lock: ['delete'],
    },
    {
      name: 'DVF record',
      alias: 'dvf_record_id',
      type: 'integer',
      __lock: ['delete'],
    },
  ],
  views: [
    {
      name: 'Default',
      alias: 'default',
      type: 'grid',
      condition_script: 'p.currentUser.isAdmin()',
      layout: 'Default',
      filter: 'Default',
      __lock: ['delete'],
    },
  ],
  layouts: [
    {
      name: 'Default',
      type: 'grid',
      options: {
        columns: [
          'id',
          'dtf_field_id',
          'dtf_record_id',
          'data_model_id',
          'data_record_id',
          'dvf_field_id',
          'dvf_record_id',
          'created_at',
          'created_by',
          'updated_at',
          'updated_by',
        ],
        columns_options: {},
        sort_order: [
          { field: 'id', type: 'descending' },
          { field: 'dtf_field_id', type: 'none' },
          { field: 'dtf_record_id', type: 'none' },
          { field: 'data_model_id', type: 'none' },
          { field: 'data_record_id', type: 'none' },
          { field: 'dvf_field_id', type: 'none' },
          { field: 'dvf_record_id', type: 'none' },
          { field: 'created_at', type: 'none' },
          { field: 'created_by', type: 'none' },
          { field: 'updated_at', type: 'none' },
          { field: 'updated_by', type: 'none' },
        ],
        wrap_text: false,
        cell_editing: false,
      },
      __lock: ['delete'],
    },
  ],
  forms: [
    {
      name: 'Default',
      alias: 'default',
      order: 0,
      active: true,
      condition_script: 'true',
      options: {
        components: {
          list: [
            '__tab__.main',
            '__section__.1',
            '__column__.1_1',
            'dtf_field_id',
            'dtf_record_id',
            'data_model_id',
            'data_record_id',
            'dvf_field_id',
            'dvf_record_id',
            '__tab__.service',
            '__section__.3',
            'id',
            '__section__.4',
            '__column__.4_1',
            'created_at',
            'updated_at',
            '__column__.4_2',
            'created_by',
            'updated_by',
          ],
          options: {
            '__tab__.main': { expanded: true, name: 'Main' },
            '__tab__.service': { name: 'Service' },
          },
        },
        related_components: { list: [], options: {} },
      },
      __lock: ['delete'],
    },
  ],
  permissions: [
    { type: 'model', action: 'create', script: 'p.currentUser.isAdmin()', __lock: ['delete'] },
    { type: 'model', action: 'update', script: 'p.currentUser.isAdmin()', __lock: ['delete'] },
    { type: 'model', action: 'delete', script: 'p.currentUser.isAdmin()', __lock: ['delete'] },
  ],
};
