export default {
  name: 'IP Ban',
  plural: 'IP Bans',
  alias: 'ip_ban',
  type: 'core',
  template: 'base',
  access_script: 'p.currentUser.canAtLeastRead()',
  order: '-100',
  audit: 'none',
  __lock: ['delete'],
  fields: [
    {
      name: 'IP',
      alias: 'ip',
      type: 'string',
      options: { length: 60 },
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Account',
      alias: 'account',
      type: 'reference',
      options: { foreign_model: 'account', foreign_label: 'email' },
      required_when_script: "p.record.getValue('ban_type') === 'account'",
      __lock: ['delete'],
    },
    {
      name: 'Ban type',
      alias: 'ban_type',
      type: 'array_string',
      options: {
        values: {
          'ip': 'IP',
          'account': 'Account',
        },
      },
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Attempts',
      alias: 'attempts',
      type: 'integer',
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Ban till',
      alias: 'ban_till',
      type: 'datetime',
      __lock: ['delete'],
    },
    {
      name: 'Ban level',
      alias: 'ban_level',
      type: 'array_string',
      options: {
        values: {
          '0': 'None',
          '1': '1 min',
          '2': '3 min',
          '3': '10 min',
          '4': '60 min',
          '5': '360 min',
        },
      },
      required_when_script: 'true',
      __lock: ['delete'],
    },
    {
      name: 'Reason',
      alias: 'reason',
      type: 'string',
      options: { length: 1024, rows: 3 },
      __lock: ['delete'],
    },
    {
      name: 'Type',
      alias: 'type',
      type: 'array_string',
      options: {
        values: {
          login: 'Login',
          password_recovery_email_protection: 'Password recovery email protection',
          password_recovery_security_code_protection: 'Password recovery security code protection',
          registration_security_code_protection: 'Registration security code protection',
        },
      },
      required_when_script: 'true',
      __lock: ['delete'],
    },
  ],
  views: [
    {
      name: 'Default',
      alias: 'default',
      type: 'grid',
      condition_script: 'p.currentUser.isAdmin()',
      layout: 'Default',
      filter: 'Default',
      __lock: ['delete'],
    },
  ],
  layouts: [
    {
      name: 'Default',
      type: 'grid',
      options: {
        columns: ['id', 'account', 'ip', 'ban_type', 'ban_till', 'attempts', 'ban_level', 'type', 'reason', 'updated_at', 'updated_by'],
        columns_options: {},
        sort_order: [
          { field: 'id', type: 'descending' },
          { field: 'account', type: 'none' },
          { field: 'ip', type: 'none' },
          { field: 'ban_type', type: 'none' },
          { field: 'ban_till', type: 'none' },
          { field: 'attempts', type: 'none' },
          { field: 'ban_level', type: 'none' },
          { field: 'type', type: 'none' },
          { field: 'reason', type: 'none' },
          { field: 'created_at', type: 'none' },
          { field: 'updated_at', type: 'none' },
        ],
        wrap_text: false,
        cell_editing: false,
      },
      __lock: ['delete'],
    },
  ],
  forms: [
    {
      name: 'Default',
      alias: 'default',
      order: 0,
      active: true,
      condition_script: 'p.currentUser.isAdmin()',
      options: {
        components: {
          list: [
            '__tab__.main',
            '__section__.1',
            '__column__.1_1',
            'account',
            'ban_type',
            'attempts',
            '__column__.1_2',
            'ip',
            'ban_till',
            'ban_level',
            '__section__.2',
            'type',
            'reason',
            '__tab__.service',
            '__section__.3',
            'id',
            '__section__.4',
            '__column__.4_1',
            'created_at',
            'updated_at',
            '__column__.4_2',
            'created_by',
            'updated_by',
          ],
          options: {
            '__tab__.main': { expanded: true, name: 'Main' },
            '__tab__.service': { name: 'Service' },
          },
        },
        related_components: { list: [], options: {} },
      },
      __lock: ['delete'],
    },
  ],
  permissions: [
    { type: 'model', action: 'create', script: 'p.currentUser.isAdmin()', __lock: ['delete'] },
    { type: 'model', action: 'update', script: 'p.currentUser.isAdmin()', __lock: ['delete'] },
    { type: 'model', action: 'delete', script: 'p.currentUser.isAdmin()', __lock: ['delete'] },
  ],
};
