version: "3.8"

services:
  nginx:
    build: .
    image: plasticine/nginx
    container_name: nginx
    volumes:
      - ./etc/nginx/conf.d/default.conf.template:/etc/nginx/conf.d/default.conf.template
    ports:
      - "${SERVICE_PORT}:80"
    environment:
      SERVICE_BACKEND_URL: ${SERVICE_BACKEND_URL}
      SERVICE_FRONTEND_URL: ${SERVICE_FRONTEND_URL}
    restart: unless-stopped

networks:
  default:
    name: plasticine