export const APP_INITIALIZED = 'APP_INITIALIZED',
  APP_USER_FULFILLED = 'APP_USER_FULFILLED',
  APP_OPTIONS_UPDATED = 'APP_OPTIONS_UPDATED',
  APP_COMPONENT_READY = 'APP_COMPONENT_READY',
  APP_THEME_CHANGED = 'APP_THEME_CHANGED',
  USER_AUTHORIZED = 'USER_AUTHORIZED',
  USER_LOGGED_OUT = 'USER_LOGGED_OUT',
  ERROR = 'ERROR';

export const WS_CONNECT = 'WS_CONNECT',
  WS_DISCONNECT = 'WS_DISCONNECT',
  WS_CONNECTED = 'WS_CONNECTED',
  WS_DISCONNECTED = 'WS_DISCONNECTED';

export const RECORDS_FULFILLED = 'RECORDS_FULFILLED';
export const APP_METADATA_FULFILLED = 'APP_METADATA_FULFILLED',
  APP_METADATA_FULFILLED_REWRITE = 'APP_METADATA_FULFILLED_REWRITE',
  METADATA_FULFILLED = 'METADATA_FULFILLED';

export const SYSTEM_SIDEBAR_UPDATED = 'SYSTEM_SIDEBAR_UPDATED';

export const CONTENT_CLOSED = 'CONTENT_CLOSED',
  CONTENT_PENDING = 'CONTENT_PENDING',
  CONTENT_FULFILLED = 'CONTENT_FULFILLED',
  VIEW_COUNT_FULFILLED = 'VIEW_COUNT_FULFILLED',
  CONTENT_REJECTED = 'CONTENT_REJECTED';

export const FORM_RECORD_UPDATED = 'FORM_RECORD_UPDATED',
  RECORD_SIBLINGS_FULFILLED = 'RECORD_SIBLINGS_FULFILLED';

export const FIELD_PENDING = 'FIELD_PENDING',
  FIELD_FULFILLED = 'FIELD_FULFILLED',
  FIELD_CLOSED = 'FIELD_CLOSED';

export const ACTION_PENDING = 'ACTION_PENDING',
  ACTION_FULFILLED = 'ACTION_FULFILLED',
  ACTION_REJECTED = 'ACTION_REJECTED',
  ACTION_CANCELED = 'ACTION_CANCELED',
  ACTION_RESPOND_WITH_DATA = 'ACTION_RESPOND_WITH_DATA',
  ACTION_RESPOND_WITH_ERROR = 'ACTION_RESPOND_WITH_ERROR';

export const CONTENT_CHANGED = 'CONTENT_CHANGED';

export const UPDATE_STORE = 'UPDATE_STORE';
export const SET_SCHEDULED_REQUEST = 'SET_SCHEDULED_REQUEST';
export const REMOVE_SCHEDULED_REQUEST = 'REMOVE_SCHEDULED_REQUEST';
export const LOCATION_CHANGED = 'LOCATION_CHANGED';

export const EXPORT_FORM_RELATED_VIEW_PARAMS = 'EXPORT_FORM_RELATED_VIEW_PARAMS';