version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2022-01-27T03-53-02Z.fips
    container_name: minio
    volumes:
      - ./root/.minio:/root/.minio
      - ./export:/export
      - ./data:/data
    command: "server --console-address :${SERVICE_CONSOLE_PORT} /export"
    ports:
      - '${SERVICE_PORT}:9000'
    environment:
      MINIO_ROOT_USER: "${MINIO_ROOT_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_ROOT_PASSWORD}"

networks:
  default:
    name: plasticine