apiVersion: v1
kind: Secret
metadata:
  name: secret-{{ .Values.Name }}
type: Opaque
stringData:
  DEBUG:                        {{ .Values.services.backend.environment.DEBUG | default "0" | quote }}
  NODE_TLS_REJECT_UNAUTHORIZED: {{ .Values.services.backend.environment.NODE_TLS_REJECT_UNAUTHORIZED | default "0" | quote }}
  APP_ENV:                      {{ .Values.services.backend.environment.APP_ENV }}
  APP_NAME:                     {{ .Values.services.backend.environment.APP_NAME }}
  APP_SECRET:                   {{ .Values.services.backend.environment.APP_SECRET }}
  APP_HOST_NAME:                {{ .Values.services.backend.environment.APP_HOST_NAME }}
  APP_HOST_PROTOCOL:            {{ .Values.services.backend.environment.APP_HOST_PROTOCOL }}
  APP_ADMIN_USER:               {{ .Values.services.backend.environment.APP_ADMIN_USER }}
  APP_ADMIN_PASS:               {{ .Values.services.backend.environment.APP_ADMIN_PASS }}
  APP_MAILER_USER:              {{ .Values.services.backend.environment.APP_MAILER_USER }}
  APP_MAILER_PASS:              {{ .Values.services.backend.environment.APP_MAILER_PASS }}
  AWS_ROLE_ARN:                 {{ .Values.services.backend.environment.AWS_ROLE_ARN | default "" | quote }}
  AWS_ACCESS_KEY_ID:            {{ .Values.services.backend.environment.AWS_ACCESS_KEY_ID | default "" | quote }}
  AWS_SECRET_ACCESS_KEY:        {{ .Values.services.backend.environment.AWS_SECRET_ACCESS_KEY | default "" | quote }}
  DB_TYPE:                      {{ .Values.services.backend.environment.DB_TYPE }}
  DB_HOST:                      {{ .Values.services.backend.environment.DB_HOST }}
  DB_PORT:                      {{ .Values.services.backend.environment.DB_PORT | quote }}
  DB_NAME:                      {{ .Values.services.backend.environment.DB_NAME }}
  DB_USER:                      {{ .Values.services.backend.environment.DB_USER }}
  DB_PASS:                      {{ .Values.services.backend.environment.DB_PASS }}
  DB_SSL:                       {{ .Values.services.backend.environment.DB_SSL | quote }}
  DB_TZ:                        {{ .Values.services.backend.environment.DB_TZ }}
  STORAGE_TYPE:                 {{ .Values.services.backend.environment.STORAGE_TYPE }}
  STORAGE_HOST:                 {{ .Values.services.backend.environment.STORAGE_HOST }}
  STORAGE_PORT:                 {{ .Values.services.backend.environment.STORAGE_PORT | quote }}
  STORAGE_BUCKET:               {{ .Values.services.backend.environment.STORAGE_BUCKET }}
  STORAGE_ACCESS_KEY:           {{ .Values.services.backend.environment.STORAGE_ACCESS_KEY | default "" | quote }}
  STORAGE_SECRET_KEY:           {{ .Values.services.backend.environment.STORAGE_SECRET_KEY | default "" | quote }}
  STORAGE_REGION:               {{ .Values.services.backend.environment.STORAGE_REGION }}
  STORAGE_SSL:                  {{ .Values.services.backend.environment.STORAGE_SSL | quote }}
  STORAGE_PART_SIZE:            {{ .Values.services.backend.environment.STORAGE_PART_SIZE | default "1048576000" | quote }}
  STORAGE_PART_STYLE:           {{ .Values.services.backend.environment.STORAGE_PART_STYLE | default "1048576000" | quote }}
  REDIS_CORE_HOST:              {{ .Values.services.backend.environment.REDIS_CORE_HOST }}
  REDIS_CUSTOM_HOST:            {{ .Values.services.backend.environment.REDIS_CUSTOM_HOST }}
  SERVICE_FRONTEND_HOST:        {{ .Values.services.backend.environment.SERVICE_FRONTEND_HOST }}
  SERVICE_FRONTEND_PORT:        {{ .Values.services.backend.environment.SERVICE_FRONTEND_PORT | quote }}
  SERVICE_LIBREOFFICE_HOST:        {{ .Values.services.backend.environment.SERVICE_LIBREOFFICE_HOST }}
  SERVICE_LIBREOFFICE_PORT:        {{ .Values.services.backend.environment.SERVICE_LIBREOFFICE_PORT | quote }}