apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Name }}
spec:
  type: ClusterIP
  selector:
    service: {{ .Values.Name }}
  ports:
    - name: {{ .Values.Name }}
      port: {{ .Values.ServiceExternalPort }}
      targetPort: {{ .Values.Name }}
      protocol: TCP
