export default {
  "font-awesome": {
    "svg": {
      "500px": require("../../assets/font-awesome/svg/500px.svg"),
      "address book outline": require("../../assets/font-awesome/svg/address-book-o.svg"),
      "address book": require("../../assets/font-awesome/svg/address-book.svg"),
      "address card outline": require("../../assets/font-awesome/svg/address-card-o.svg"),
      "address card": require("../../assets/font-awesome/svg/address-card.svg"),
      "adjust": require("../../assets/font-awesome/svg/adjust.svg"),
      "adn": require("../../assets/font-awesome/svg/adn.svg"),
      "align center": require("../../assets/font-awesome/svg/align-center.svg"),
      "align justify": require("../../assets/font-awesome/svg/align-justify.svg"),
      "align left": require("../../assets/font-awesome/svg/align-left.svg"),
      "align right": require("../../assets/font-awesome/svg/align-right.svg"),
      "amazon": require("../../assets/font-awesome/svg/amazon.svg"),
      "ambulance": require("../../assets/font-awesome/svg/ambulance.svg"),
      "american sign language interpreting": require("../../assets/font-awesome/svg/american-sign-language-interpreting.svg"),
      "anchor": require("../../assets/font-awesome/svg/anchor.svg"),
      "android": require("../../assets/font-awesome/svg/android.svg"),
      "angellist": require("../../assets/font-awesome/svg/angellist.svg"),
      "angle double down": require("../../assets/font-awesome/svg/angle-double-down.svg"),
      "angle double left": require("../../assets/font-awesome/svg/angle-double-left.svg"),
      "angle double right": require("../../assets/font-awesome/svg/angle-double-right.svg"),
      "angle double up": require("../../assets/font-awesome/svg/angle-double-up.svg"),
      "angle down": require("../../assets/font-awesome/svg/angle-down.svg"),
      "angle left": require("../../assets/font-awesome/svg/angle-left.svg"),
      "angle right": require("../../assets/font-awesome/svg/angle-right.svg"),
      "angle up": require("../../assets/font-awesome/svg/angle-up.svg"),
      "apple": require("../../assets/font-awesome/svg/apple.svg"),
      "archive": require("../../assets/font-awesome/svg/archive.svg"),
      "area chart": require("../../assets/font-awesome/svg/area-chart.svg"),
      "arrow circle down": require("../../assets/font-awesome/svg/arrow-circle-down.svg"),
      "arrow circle left": require("../../assets/font-awesome/svg/arrow-circle-left.svg"),
      "arrow circle o down": require("../../assets/font-awesome/svg/arrow-circle-o-down.svg"),
      "arrow circle o left": require("../../assets/font-awesome/svg/arrow-circle-o-left.svg"),
      "arrow circle o right": require("../../assets/font-awesome/svg/arrow-circle-o-right.svg"),
      "arrow circle o up": require("../../assets/font-awesome/svg/arrow-circle-o-up.svg"),
      "arrow circle right": require("../../assets/font-awesome/svg/arrow-circle-right.svg"),
      "arrow circle up": require("../../assets/font-awesome/svg/arrow-circle-up.svg"),
      "arrow down": require("../../assets/font-awesome/svg/arrow-down.svg"),
      "arrow left": require("../../assets/font-awesome/svg/arrow-left.svg"),
      "arrow right": require("../../assets/font-awesome/svg/arrow-right.svg"),
      "arrow up": require("../../assets/font-awesome/svg/arrow-up.svg"),
      "arrows alt": require("../../assets/font-awesome/svg/arrows-alt.svg"),
      "arrows h": require("../../assets/font-awesome/svg/arrows-h.svg"),
      "arrows v": require("../../assets/font-awesome/svg/arrows-v.svg"),
      "arrows": require("../../assets/font-awesome/svg/arrows.svg"),
      "asl interpreting": require("../../assets/font-awesome/svg/asl-interpreting.svg"),
      "assistive listening systems": require("../../assets/font-awesome/svg/assistive-listening-systems.svg"),
      "asterisk": require("../../assets/font-awesome/svg/asterisk.svg"),
      "at": require("../../assets/font-awesome/svg/at.svg"),
      "audio description": require("../../assets/font-awesome/svg/audio-description.svg"),
      "automobile": require("../../assets/font-awesome/svg/automobile.svg"),
      "backward": require("../../assets/font-awesome/svg/backward.svg"),
      "balance scale": require("../../assets/font-awesome/svg/balance-scale.svg"),
      "ban": require("../../assets/font-awesome/svg/ban.svg"),
      "bandcamp": require("../../assets/font-awesome/svg/bandcamp.svg"),
      "bank": require("../../assets/font-awesome/svg/bank.svg"),
      "bar chart outline": require("../../assets/font-awesome/svg/bar-chart-o.svg"),
      "bar chart": require("../../assets/font-awesome/svg/bar-chart.svg"),
      "barcode": require("../../assets/font-awesome/svg/barcode.svg"),
      "bars": require("../../assets/font-awesome/svg/bars.svg"),
      "bath": require("../../assets/font-awesome/svg/bath.svg"),
      "bathtub": require("../../assets/font-awesome/svg/bathtub.svg"),
      "battery 0": require("../../assets/font-awesome/svg/battery-0.svg"),
      "battery 1": require("../../assets/font-awesome/svg/battery-1.svg"),
      "battery 2": require("../../assets/font-awesome/svg/battery-2.svg"),
      "battery 3": require("../../assets/font-awesome/svg/battery-3.svg"),
      "battery 4": require("../../assets/font-awesome/svg/battery-4.svg"),
      "battery empty": require("../../assets/font-awesome/svg/battery-empty.svg"),
      "battery full": require("../../assets/font-awesome/svg/battery-full.svg"),
      "battery half": require("../../assets/font-awesome/svg/battery-half.svg"),
      "battery quarter": require("../../assets/font-awesome/svg/battery-quarter.svg"),
      "battery three quarters": require("../../assets/font-awesome/svg/battery-three-quarters.svg"),
      "battery": require("../../assets/font-awesome/svg/battery.svg"),
      "bed": require("../../assets/font-awesome/svg/bed.svg"),
      "beer": require("../../assets/font-awesome/svg/beer.svg"),
      "behance square": require("../../assets/font-awesome/svg/behance-square.svg"),
      "behance": require("../../assets/font-awesome/svg/behance.svg"),
      "bell outline": require("../../assets/font-awesome/svg/bell-o.svg"),
      "bell slash outline": require("../../assets/font-awesome/svg/bell-slash-o.svg"),
      "bell slash": require("../../assets/font-awesome/svg/bell-slash.svg"),
      "bell": require("../../assets/font-awesome/svg/bell.svg"),
      "bicycle": require("../../assets/font-awesome/svg/bicycle.svg"),
      "binoculars": require("../../assets/font-awesome/svg/binoculars.svg"),
      "birthday cake": require("../../assets/font-awesome/svg/birthday-cake.svg"),
      "bitbucket square": require("../../assets/font-awesome/svg/bitbucket-square.svg"),
      "bitbucket": require("../../assets/font-awesome/svg/bitbucket.svg"),
      "bitcoin": require("../../assets/font-awesome/svg/bitcoin.svg"),
      "black tie": require("../../assets/font-awesome/svg/black-tie.svg"),
      "blind": require("../../assets/font-awesome/svg/blind.svg"),
      "bluetooth b": require("../../assets/font-awesome/svg/bluetooth-b.svg"),
      "bluetooth": require("../../assets/font-awesome/svg/bluetooth.svg"),
      "bold": require("../../assets/font-awesome/svg/bold.svg"),
      "bolt": require("../../assets/font-awesome/svg/bolt.svg"),
      "bomb": require("../../assets/font-awesome/svg/bomb.svg"),
      "book": require("../../assets/font-awesome/svg/book.svg"),
      "bookmark outline": require("../../assets/font-awesome/svg/bookmark-o.svg"),
      "bookmark": require("../../assets/font-awesome/svg/bookmark.svg"),
      "braille": require("../../assets/font-awesome/svg/braille.svg"),
      "briefcase": require("../../assets/font-awesome/svg/briefcase.svg"),
      "btc": require("../../assets/font-awesome/svg/btc.svg"),
      "bug": require("../../assets/font-awesome/svg/bug.svg"),
      "building outline": require("../../assets/font-awesome/svg/building-o.svg"),
      "building": require("../../assets/font-awesome/svg/building.svg"),
      "bullhorn": require("../../assets/font-awesome/svg/bullhorn.svg"),
      "bullseye": require("../../assets/font-awesome/svg/bullseye.svg"),
      "bus": require("../../assets/font-awesome/svg/bus.svg"),
      "buysellads": require("../../assets/font-awesome/svg/buysellads.svg"),
      "cab": require("../../assets/font-awesome/svg/cab.svg"),
      "calculator": require("../../assets/font-awesome/svg/calculator.svg"),
      "calendar check outline": require("../../assets/font-awesome/svg/calendar-check-o.svg"),
      "calendar minus outline": require("../../assets/font-awesome/svg/calendar-minus-o.svg"),
      "calendar outline": require("../../assets/font-awesome/svg/calendar-o.svg"),
      "calendar plus outline": require("../../assets/font-awesome/svg/calendar-plus-o.svg"),
      "calendar times outline": require("../../assets/font-awesome/svg/calendar-times-o.svg"),
      "calendar": require("../../assets/font-awesome/svg/calendar.svg"),
      "camera retroutline": require("../../assets/font-awesome/svg/camera-retro.svg"),
      "camera": require("../../assets/font-awesome/svg/camera.svg"),
      "car": require("../../assets/font-awesome/svg/car.svg"),
      "caret down": require("../../assets/font-awesome/svg/caret-down.svg"),
      "caret left": require("../../assets/font-awesome/svg/caret-left.svg"),
      "caret right": require("../../assets/font-awesome/svg/caret-right.svg"),
      "caret square o down": require("../../assets/font-awesome/svg/caret-square-o-down.svg"),
      "caret square o left": require("../../assets/font-awesome/svg/caret-square-o-left.svg"),
      "caret square o right": require("../../assets/font-awesome/svg/caret-square-o-right.svg"),
      "caret square o up": require("../../assets/font-awesome/svg/caret-square-o-up.svg"),
      "caret up": require("../../assets/font-awesome/svg/caret-up.svg"),
      "cart arrow down": require("../../assets/font-awesome/svg/cart-arrow-down.svg"),
      "cart plus": require("../../assets/font-awesome/svg/cart-plus.svg"),
      "cc amex": require("../../assets/font-awesome/svg/cc-amex.svg"),
      "cc diners club": require("../../assets/font-awesome/svg/cc-diners-club.svg"),
      "cc discover": require("../../assets/font-awesome/svg/cc-discover.svg"),
      "cc jcb": require("../../assets/font-awesome/svg/cc-jcb.svg"),
      "cc mastercard": require("../../assets/font-awesome/svg/cc-mastercard.svg"),
      "cc paypal": require("../../assets/font-awesome/svg/cc-paypal.svg"),
      "cc stripe": require("../../assets/font-awesome/svg/cc-stripe.svg"),
      "cc visa": require("../../assets/font-awesome/svg/cc-visa.svg"),
      "cc": require("../../assets/font-awesome/svg/cc.svg"),
      "certificate": require("../../assets/font-awesome/svg/certificate.svg"),
      "chain broken": require("../../assets/font-awesome/svg/chain-broken.svg"),
      "chain": require("../../assets/font-awesome/svg/chain.svg"),
      "check circle outline": require("../../assets/font-awesome/svg/check-circle-o.svg"),
      "check circle": require("../../assets/font-awesome/svg/check-circle.svg"),
      "check square outline": require("../../assets/font-awesome/svg/check-square-o.svg"),
      "check square": require("../../assets/font-awesome/svg/check-square.svg"),
      "check": require("../../assets/font-awesome/svg/check.svg"),
      "chevron circle down": require("../../assets/font-awesome/svg/chevron-circle-down.svg"),
      "chevron circle left": require("../../assets/font-awesome/svg/chevron-circle-left.svg"),
      "chevron circle right": require("../../assets/font-awesome/svg/chevron-circle-right.svg"),
      "chevron circle up": require("../../assets/font-awesome/svg/chevron-circle-up.svg"),
      "chevron down": require("../../assets/font-awesome/svg/chevron-down.svg"),
      "chevron left": require("../../assets/font-awesome/svg/chevron-left.svg"),
      "chevron right": require("../../assets/font-awesome/svg/chevron-right.svg"),
      "chevron up": require("../../assets/font-awesome/svg/chevron-up.svg"),
      "child": require("../../assets/font-awesome/svg/child.svg"),
      "chrome": require("../../assets/font-awesome/svg/chrome.svg"),
      "circle o notch": require("../../assets/font-awesome/svg/circle-o-notch.svg"),
      "circle outline": require("../../assets/font-awesome/svg/circle-o.svg"),
      "circle thin": require("../../assets/font-awesome/svg/circle-thin.svg"),
      "circle": require("../../assets/font-awesome/svg/circle.svg"),
      "clipboard": require("../../assets/font-awesome/svg/clipboard.svg"),
      "clock outline": require("../../assets/font-awesome/svg/clock-o.svg"),
      "clone": require("../../assets/font-awesome/svg/clone.svg"),
      "close": require("../../assets/font-awesome/svg/close.svg"),
      "cloud download": require("../../assets/font-awesome/svg/cloud-download.svg"),
      "cloud upload": require("../../assets/font-awesome/svg/cloud-upload.svg"),
      "cloud": require("../../assets/font-awesome/svg/cloud.svg"),
      "cny": require("../../assets/font-awesome/svg/cny.svg"),
      "code fork": require("../../assets/font-awesome/svg/code-fork.svg"),
      "code": require("../../assets/font-awesome/svg/code.svg"),
      "codepen": require("../../assets/font-awesome/svg/codepen.svg"),
      "codiepie": require("../../assets/font-awesome/svg/codiepie.svg"),
      "coffee": require("../../assets/font-awesome/svg/coffee.svg"),
      "cog": require("../../assets/font-awesome/svg/cog.svg"),
      "cogs": require("../../assets/font-awesome/svg/cogs.svg"),
      "columns": require("../../assets/font-awesome/svg/columns.svg"),
      "comment outline": require("../../assets/font-awesome/svg/comment-o.svg"),
      "comment": require("../../assets/font-awesome/svg/comment.svg"),
      "commenting outline": require("../../assets/font-awesome/svg/commenting-o.svg"),
      "commenting": require("../../assets/font-awesome/svg/commenting.svg"),
      "comments outline": require("../../assets/font-awesome/svg/comments-o.svg"),
      "comments": require("../../assets/font-awesome/svg/comments.svg"),
      "compass": require("../../assets/font-awesome/svg/compass.svg"),
      "compress": require("../../assets/font-awesome/svg/compress.svg"),
      "connectdevelop": require("../../assets/font-awesome/svg/connectdevelop.svg"),
      "contaoutline": require("../../assets/font-awesome/svg/contao.svg"),
      "copy": require("../../assets/font-awesome/svg/copy.svg"),
      "copyright": require("../../assets/font-awesome/svg/copyright.svg"),
      "creative commons": require("../../assets/font-awesome/svg/creative-commons.svg"),
      "credit card alt": require("../../assets/font-awesome/svg/credit-card-alt.svg"),
      "credit card": require("../../assets/font-awesome/svg/credit-card.svg"),
      "crop": require("../../assets/font-awesome/svg/crop.svg"),
      "crosshairs": require("../../assets/font-awesome/svg/crosshairs.svg"),
      "css3": require("../../assets/font-awesome/svg/css3.svg"),
      "cube": require("../../assets/font-awesome/svg/cube.svg"),
      "cubes": require("../../assets/font-awesome/svg/cubes.svg"),
      "cut": require("../../assets/font-awesome/svg/cut.svg"),
      "cutlery": require("../../assets/font-awesome/svg/cutlery.svg"),
      "dashboard": require("../../assets/font-awesome/svg/dashboard.svg"),
      "dashcube": require("../../assets/font-awesome/svg/dashcube.svg"),
      "database": require("../../assets/font-awesome/svg/database.svg"),
      "deaf": require("../../assets/font-awesome/svg/deaf.svg"),
      "deafness": require("../../assets/font-awesome/svg/deafness.svg"),
      "dedent": require("../../assets/font-awesome/svg/dedent.svg"),
      "delicious": require("../../assets/font-awesome/svg/delicious.svg"),
      "desktop": require("../../assets/font-awesome/svg/desktop.svg"),
      "deviantart": require("../../assets/font-awesome/svg/deviantart.svg"),
      "diamond": require("../../assets/font-awesome/svg/diamond.svg"),
      "digg": require("../../assets/font-awesome/svg/digg.svg"),
      "dollar": require("../../assets/font-awesome/svg/dollar.svg"),
      "dot circle outline": require("../../assets/font-awesome/svg/dot-circle-o.svg"),
      "download": require("../../assets/font-awesome/svg/download.svg"),
      "dribbble": require("../../assets/font-awesome/svg/dribbble.svg"),
      "drivers license outline": require("../../assets/font-awesome/svg/drivers-license-o.svg"),
      "drivers license": require("../../assets/font-awesome/svg/drivers-license.svg"),
      "dropbox": require("../../assets/font-awesome/svg/dropbox.svg"),
      "drupal": require("../../assets/font-awesome/svg/drupal.svg"),
      "edge": require("../../assets/font-awesome/svg/edge.svg"),
      "edit": require("../../assets/font-awesome/svg/edit.svg"),
      "eercast": require("../../assets/font-awesome/svg/eercast.svg"),
      "eject": require("../../assets/font-awesome/svg/eject.svg"),
      "ellipsis h": require("../../assets/font-awesome/svg/ellipsis-h.svg"),
      "ellipsis v": require("../../assets/font-awesome/svg/ellipsis-v.svg"),
      "empire": require("../../assets/font-awesome/svg/empire.svg"),
      "envelope outline": require("../../assets/font-awesome/svg/envelope-o.svg"),
      "envelope open outline": require("../../assets/font-awesome/svg/envelope-open-o.svg"),
      "envelope open": require("../../assets/font-awesome/svg/envelope-open.svg"),
      "envelope square": require("../../assets/font-awesome/svg/envelope-square.svg"),
      "envelope": require("../../assets/font-awesome/svg/envelope.svg"),
      "envira": require("../../assets/font-awesome/svg/envira.svg"),
      "eraser": require("../../assets/font-awesome/svg/eraser.svg"),
      "etsy": require("../../assets/font-awesome/svg/etsy.svg"),
      "eur": require("../../assets/font-awesome/svg/eur.svg"),
      "euroutline": require("../../assets/font-awesome/svg/euro.svg"),
      "exchange": require("../../assets/font-awesome/svg/exchange.svg"),
      "exclamation circle": require("../../assets/font-awesome/svg/exclamation-circle.svg"),
      "exclamation triangle": require("../../assets/font-awesome/svg/exclamation-triangle.svg"),
      "exclamation": require("../../assets/font-awesome/svg/exclamation.svg"),
      "expand": require("../../assets/font-awesome/svg/expand.svg"),
      "expeditedssl": require("../../assets/font-awesome/svg/expeditedssl.svg"),
      "external link square": require("../../assets/font-awesome/svg/external-link-square.svg"),
      "external link": require("../../assets/font-awesome/svg/external-link.svg"),
      "eye slash": require("../../assets/font-awesome/svg/eye-slash.svg"),
      "eye": require("../../assets/font-awesome/svg/eye.svg"),
      "eyedropper": require("../../assets/font-awesome/svg/eyedropper.svg"),
      "fa": require("../../assets/font-awesome/svg/fa.svg"),
      "facebook f": require("../../assets/font-awesome/svg/facebook-f.svg"),
      "facebook official": require("../../assets/font-awesome/svg/facebook-official.svg"),
      "facebook square": require("../../assets/font-awesome/svg/facebook-square.svg"),
      "facebook": require("../../assets/font-awesome/svg/facebook.svg"),
      "fast backward": require("../../assets/font-awesome/svg/fast-backward.svg"),
      "fast forward": require("../../assets/font-awesome/svg/fast-forward.svg"),
      "fax": require("../../assets/font-awesome/svg/fax.svg"),
      "feed": require("../../assets/font-awesome/svg/feed.svg"),
      "female": require("../../assets/font-awesome/svg/female.svg"),
      "fighter jet": require("../../assets/font-awesome/svg/fighter-jet.svg"),
      "file archive outline": require("../../assets/font-awesome/svg/file-archive-o.svg"),
      "file audio outline": require("../../assets/font-awesome/svg/file-audio-o.svg"),
      "file code outline": require("../../assets/font-awesome/svg/file-code-o.svg"),
      "file excel outline": require("../../assets/font-awesome/svg/file-excel-o.svg"),
      "file image outline": require("../../assets/font-awesome/svg/file-image-o.svg"),
      "file movie outline": require("../../assets/font-awesome/svg/file-movie-o.svg"),
      "file outline": require("../../assets/font-awesome/svg/file-o.svg"),
      "file pdf outline": require("../../assets/font-awesome/svg/file-pdf-o.svg"),
      "file photo outline": require("../../assets/font-awesome/svg/file-photo-o.svg"),
      "file picture outline": require("../../assets/font-awesome/svg/file-picture-o.svg"),
      "file powerpoint outline": require("../../assets/font-awesome/svg/file-powerpoint-o.svg"),
      "file sound outline": require("../../assets/font-awesome/svg/file-sound-o.svg"),
      "file text outline": require("../../assets/font-awesome/svg/file-text-o.svg"),
      "file text": require("../../assets/font-awesome/svg/file-text.svg"),
      "file video outline": require("../../assets/font-awesome/svg/file-video-o.svg"),
      "file word outline": require("../../assets/font-awesome/svg/file-word-o.svg"),
      "file zip outline": require("../../assets/font-awesome/svg/file-zip-o.svg"),
      "file": require("../../assets/font-awesome/svg/file.svg"),
      "files outline": require("../../assets/font-awesome/svg/files-o.svg"),
      "film": require("../../assets/font-awesome/svg/film.svg"),
      "filter": require("../../assets/font-awesome/svg/filter.svg"),
      "fire extinguisher": require("../../assets/font-awesome/svg/fire-extinguisher.svg"),
      "fire": require("../../assets/font-awesome/svg/fire.svg"),
      "firefox": require("../../assets/font-awesome/svg/firefox.svg"),
      "first order": require("../../assets/font-awesome/svg/first-order.svg"),
      "flag checkered": require("../../assets/font-awesome/svg/flag-checkered.svg"),
      "flag outline": require("../../assets/font-awesome/svg/flag-o.svg"),
      "flag": require("../../assets/font-awesome/svg/flag.svg"),
      "flash": require("../../assets/font-awesome/svg/flash.svg"),
      "flask": require("../../assets/font-awesome/svg/flask.svg"),
      "flickr": require("../../assets/font-awesome/svg/flickr.svg"),
      "floppy outline": require("../../assets/font-awesome/svg/floppy-o.svg"),
      "folder outline": require("../../assets/font-awesome/svg/folder-o.svg"),
      "folder open outline": require("../../assets/font-awesome/svg/folder-open-o.svg"),
      "folder open": require("../../assets/font-awesome/svg/folder-open.svg"),
      "folder": require("../../assets/font-awesome/svg/folder.svg"),
      "font awesome": require("../../assets/font-awesome/svg/font-awesome.svg"),
      "font": require("../../assets/font-awesome/svg/font.svg"),
      "fonticons": require("../../assets/font-awesome/svg/fonticons.svg"),
      "fort awesome": require("../../assets/font-awesome/svg/fort-awesome.svg"),
      "forumbee": require("../../assets/font-awesome/svg/forumbee.svg"),
      "forward": require("../../assets/font-awesome/svg/forward.svg"),
      "foursquare": require("../../assets/font-awesome/svg/foursquare.svg"),
      "free code camp": require("../../assets/font-awesome/svg/free-code-camp.svg"),
      "frown outline": require("../../assets/font-awesome/svg/frown-o.svg"),
      "futbol outline": require("../../assets/font-awesome/svg/futbol-o.svg"),
      "gamepad": require("../../assets/font-awesome/svg/gamepad.svg"),
      "gavel": require("../../assets/font-awesome/svg/gavel.svg"),
      "gbp": require("../../assets/font-awesome/svg/gbp.svg"),
      "ge": require("../../assets/font-awesome/svg/ge.svg"),
      "gear": require("../../assets/font-awesome/svg/gear.svg"),
      "gears": require("../../assets/font-awesome/svg/gears.svg"),
      "genderless": require("../../assets/font-awesome/svg/genderless.svg"),
      "get pocket": require("../../assets/font-awesome/svg/get-pocket.svg"),
      "gg circle": require("../../assets/font-awesome/svg/gg-circle.svg"),
      "gg": require("../../assets/font-awesome/svg/gg.svg"),
      "gift": require("../../assets/font-awesome/svg/gift.svg"),
      "git square": require("../../assets/font-awesome/svg/git-square.svg"),
      "git": require("../../assets/font-awesome/svg/git.svg"),
      "github alt": require("../../assets/font-awesome/svg/github-alt.svg"),
      "github square": require("../../assets/font-awesome/svg/github-square.svg"),
      "github": require("../../assets/font-awesome/svg/github.svg"),
      "gitlab": require("../../assets/font-awesome/svg/gitlab.svg"),
      "gittip": require("../../assets/font-awesome/svg/gittip.svg"),
      "glass": require("../../assets/font-awesome/svg/glass.svg"),
      "glide g": require("../../assets/font-awesome/svg/glide-g.svg"),
      "glide": require("../../assets/font-awesome/svg/glide.svg"),
      "globe": require("../../assets/font-awesome/svg/globe.svg"),
      "google plus circle": require("../../assets/font-awesome/svg/google-plus-circle.svg"),
      "google plus official": require("../../assets/font-awesome/svg/google-plus-official.svg"),
      "google plus square": require("../../assets/font-awesome/svg/google-plus-square.svg"),
      "google plus": require("../../assets/font-awesome/svg/google-plus.svg"),
      "google wallet": require("../../assets/font-awesome/svg/google-wallet.svg"),
      "google": require("../../assets/font-awesome/svg/google.svg"),
      "graduation cap": require("../../assets/font-awesome/svg/graduation-cap.svg"),
      "gratipay": require("../../assets/font-awesome/svg/gratipay.svg"),
      "grav": require("../../assets/font-awesome/svg/grav.svg"),
      "group": require("../../assets/font-awesome/svg/group.svg"),
      "h square": require("../../assets/font-awesome/svg/h-square.svg"),
      "hacker news": require("../../assets/font-awesome/svg/hacker-news.svg"),
      "hand grab outline": require("../../assets/font-awesome/svg/hand-grab-o.svg"),
      "hand lizard outline": require("../../assets/font-awesome/svg/hand-lizard-o.svg"),
      "hand o down": require("../../assets/font-awesome/svg/hand-o-down.svg"),
      "hand o left": require("../../assets/font-awesome/svg/hand-o-left.svg"),
      "hand o right": require("../../assets/font-awesome/svg/hand-o-right.svg"),
      "hand o up": require("../../assets/font-awesome/svg/hand-o-up.svg"),
      "hand paper outline": require("../../assets/font-awesome/svg/hand-paper-o.svg"),
      "hand peace outline": require("../../assets/font-awesome/svg/hand-peace-o.svg"),
      "hand pointer outline": require("../../assets/font-awesome/svg/hand-pointer-o.svg"),
      "hand rock outline": require("../../assets/font-awesome/svg/hand-rock-o.svg"),
      "hand scissors outline": require("../../assets/font-awesome/svg/hand-scissors-o.svg"),
      "hand spock outline": require("../../assets/font-awesome/svg/hand-spock-o.svg"),
      "hand stop outline": require("../../assets/font-awesome/svg/hand-stop-o.svg"),
      "handshake outline": require("../../assets/font-awesome/svg/handshake-o.svg"),
      "hard of hearing": require("../../assets/font-awesome/svg/hard-of-hearing.svg"),
      "hashtag": require("../../assets/font-awesome/svg/hashtag.svg"),
      "hdd outline": require("../../assets/font-awesome/svg/hdd-o.svg"),
      "header": require("../../assets/font-awesome/svg/header.svg"),
      "headphones": require("../../assets/font-awesome/svg/headphones.svg"),
      "heart outline": require("../../assets/font-awesome/svg/heart-o.svg"),
      "heart": require("../../assets/font-awesome/svg/heart.svg"),
      "heartbeat": require("../../assets/font-awesome/svg/heartbeat.svg"),
      "history": require("../../assets/font-awesome/svg/history.svg"),
      "home": require("../../assets/font-awesome/svg/home.svg"),
      "hospital outline": require("../../assets/font-awesome/svg/hospital-o.svg"),
      "hotel": require("../../assets/font-awesome/svg/hotel.svg"),
      "hourglass 1": require("../../assets/font-awesome/svg/hourglass-1.svg"),
      "hourglass 2": require("../../assets/font-awesome/svg/hourglass-2.svg"),
      "hourglass 3": require("../../assets/font-awesome/svg/hourglass-3.svg"),
      "hourglass end": require("../../assets/font-awesome/svg/hourglass-end.svg"),
      "hourglass half": require("../../assets/font-awesome/svg/hourglass-half.svg"),
      "hourglass outline": require("../../assets/font-awesome/svg/hourglass-o.svg"),
      "hourglass start": require("../../assets/font-awesome/svg/hourglass-start.svg"),
      "hourglass": require("../../assets/font-awesome/svg/hourglass.svg"),
      "houzz": require("../../assets/font-awesome/svg/houzz.svg"),
      "html5": require("../../assets/font-awesome/svg/html5.svg"),
      "i cursor": require("../../assets/font-awesome/svg/i-cursor.svg"),
      "id badge": require("../../assets/font-awesome/svg/id-badge.svg"),
      "id card outline": require("../../assets/font-awesome/svg/id-card-o.svg"),
      "id card": require("../../assets/font-awesome/svg/id-card.svg"),
      "ils": require("../../assets/font-awesome/svg/ils.svg"),
      "image": require("../../assets/font-awesome/svg/image.svg"),
      "imdb": require("../../assets/font-awesome/svg/imdb.svg"),
      "inbox": require("../../assets/font-awesome/svg/inbox.svg"),
      "indent": require("../../assets/font-awesome/svg/indent.svg"),
      "industry": require("../../assets/font-awesome/svg/industry.svg"),
      "info circle": require("../../assets/font-awesome/svg/info-circle.svg"),
      "infoutline": require("../../assets/font-awesome/svg/info.svg"),
      "inr": require("../../assets/font-awesome/svg/inr.svg"),
      "instagram": require("../../assets/font-awesome/svg/instagram.svg"),
      "institution": require("../../assets/font-awesome/svg/institution.svg"),
      "internet explorer": require("../../assets/font-awesome/svg/internet-explorer.svg"),
      "intersex": require("../../assets/font-awesome/svg/intersex.svg"),
      "ioxhost": require("../../assets/font-awesome/svg/ioxhost.svg"),
      "italic": require("../../assets/font-awesome/svg/italic.svg"),
      "joomla": require("../../assets/font-awesome/svg/joomla.svg"),
      "jpy": require("../../assets/font-awesome/svg/jpy.svg"),
      "jsfiddle": require("../../assets/font-awesome/svg/jsfiddle.svg"),
      "key": require("../../assets/font-awesome/svg/key.svg"),
      "keyboard outline": require("../../assets/font-awesome/svg/keyboard-o.svg"),
      "krw": require("../../assets/font-awesome/svg/krw.svg"),
      "language": require("../../assets/font-awesome/svg/language.svg"),
      "laptop": require("../../assets/font-awesome/svg/laptop.svg"),
      "lastfm square": require("../../assets/font-awesome/svg/lastfm-square.svg"),
      "lastfm": require("../../assets/font-awesome/svg/lastfm.svg"),
      "leaf": require("../../assets/font-awesome/svg/leaf.svg"),
      "leanpub": require("../../assets/font-awesome/svg/leanpub.svg"),
      "legal": require("../../assets/font-awesome/svg/legal.svg"),
      "lemon outline": require("../../assets/font-awesome/svg/lemon-o.svg"),
      "level down": require("../../assets/font-awesome/svg/level-down.svg"),
      "level up": require("../../assets/font-awesome/svg/level-up.svg"),
      "life bouy": require("../../assets/font-awesome/svg/life-bouy.svg"),
      "life buoy": require("../../assets/font-awesome/svg/life-buoy.svg"),
      "life ring": require("../../assets/font-awesome/svg/life-ring.svg"),
      "life saver": require("../../assets/font-awesome/svg/life-saver.svg"),
      "lightbulb outline": require("../../assets/font-awesome/svg/lightbulb-o.svg"),
      "line chart": require("../../assets/font-awesome/svg/line-chart.svg"),
      "link": require("../../assets/font-awesome/svg/link.svg"),
      "linkedin square": require("../../assets/font-awesome/svg/linkedin-square.svg"),
      "linkedin": require("../../assets/font-awesome/svg/linkedin.svg"),
      "linode": require("../../assets/font-awesome/svg/linode.svg"),
      "linux": require("../../assets/font-awesome/svg/linux.svg"),
      "list alt": require("../../assets/font-awesome/svg/list-alt.svg"),
      "list ol": require("../../assets/font-awesome/svg/list-ol.svg"),
      "list ul": require("../../assets/font-awesome/svg/list-ul.svg"),
      "list": require("../../assets/font-awesome/svg/list.svg"),
      "location arrow": require("../../assets/font-awesome/svg/location-arrow.svg"),
      "lock": require("../../assets/font-awesome/svg/lock.svg"),
      "long arrow down": require("../../assets/font-awesome/svg/long-arrow-down.svg"),
      "long arrow left": require("../../assets/font-awesome/svg/long-arrow-left.svg"),
      "long arrow right": require("../../assets/font-awesome/svg/long-arrow-right.svg"),
      "long arrow up": require("../../assets/font-awesome/svg/long-arrow-up.svg"),
      "low vision": require("../../assets/font-awesome/svg/low-vision.svg"),
      "magic": require("../../assets/font-awesome/svg/magic.svg"),
      "magnet": require("../../assets/font-awesome/svg/magnet.svg"),
      "mail forward": require("../../assets/font-awesome/svg/mail-forward.svg"),
      "mail reply all": require("../../assets/font-awesome/svg/mail-reply-all.svg"),
      "mail reply": require("../../assets/font-awesome/svg/mail-reply.svg"),
      "male": require("../../assets/font-awesome/svg/male.svg"),
      "map marker": require("../../assets/font-awesome/svg/map-marker.svg"),
      "map outline": require("../../assets/font-awesome/svg/map-o.svg"),
      "map pin": require("../../assets/font-awesome/svg/map-pin.svg"),
      "map signs": require("../../assets/font-awesome/svg/map-signs.svg"),
      "map": require("../../assets/font-awesome/svg/map.svg"),
      "mars double": require("../../assets/font-awesome/svg/mars-double.svg"),
      "mars stroke h": require("../../assets/font-awesome/svg/mars-stroke-h.svg"),
      "mars stroke v": require("../../assets/font-awesome/svg/mars-stroke-v.svg"),
      "mars stroke": require("../../assets/font-awesome/svg/mars-stroke.svg"),
      "mars": require("../../assets/font-awesome/svg/mars.svg"),
      "maxcdn": require("../../assets/font-awesome/svg/maxcdn.svg"),
      "meanpath": require("../../assets/font-awesome/svg/meanpath.svg"),
      "medium": require("../../assets/font-awesome/svg/medium.svg"),
      "medkit": require("../../assets/font-awesome/svg/medkit.svg"),
      "meetup": require("../../assets/font-awesome/svg/meetup.svg"),
      "meh outline": require("../../assets/font-awesome/svg/meh-o.svg"),
      "mercury": require("../../assets/font-awesome/svg/mercury.svg"),
      "microchip": require("../../assets/font-awesome/svg/microchip.svg"),
      "microphone slash": require("../../assets/font-awesome/svg/microphone-slash.svg"),
      "microphone": require("../../assets/font-awesome/svg/microphone.svg"),
      "minus circle": require("../../assets/font-awesome/svg/minus-circle.svg"),
      "minus square outline": require("../../assets/font-awesome/svg/minus-square-o.svg"),
      "minus square": require("../../assets/font-awesome/svg/minus-square.svg"),
      "minus": require("../../assets/font-awesome/svg/minus.svg"),
      "mixcloud": require("../../assets/font-awesome/svg/mixcloud.svg"),
      "mobile phone": require("../../assets/font-awesome/svg/mobile-phone.svg"),
      "mobile": require("../../assets/font-awesome/svg/mobile.svg"),
      "modx": require("../../assets/font-awesome/svg/modx.svg"),
      "money": require("../../assets/font-awesome/svg/money.svg"),
      "moon outline": require("../../assets/font-awesome/svg/moon-o.svg"),
      "mortar board": require("../../assets/font-awesome/svg/mortar-board.svg"),
      "motorcycle": require("../../assets/font-awesome/svg/motorcycle.svg"),
      "mouse pointer": require("../../assets/font-awesome/svg/mouse-pointer.svg"),
      "music": require("../../assets/font-awesome/svg/music.svg"),
      "navicon": require("../../assets/font-awesome/svg/navicon.svg"),
      "neuter": require("../../assets/font-awesome/svg/neuter.svg"),
      "newspaper outline": require("../../assets/font-awesome/svg/newspaper-o.svg"),
      "object group": require("../../assets/font-awesome/svg/object-group.svg"),
      "object ungroup": require("../../assets/font-awesome/svg/object-ungroup.svg"),
      "odnoklassniki square": require("../../assets/font-awesome/svg/odnoklassniki-square.svg"),
      "odnoklassniki": require("../../assets/font-awesome/svg/odnoklassniki.svg"),
      "opencart": require("../../assets/font-awesome/svg/opencart.svg"),
      "openid": require("../../assets/font-awesome/svg/openid.svg"),
      "opera": require("../../assets/font-awesome/svg/opera.svg"),
      "optin monster": require("../../assets/font-awesome/svg/optin-monster.svg"),
      "outdent": require("../../assets/font-awesome/svg/outdent.svg"),
      "pagelines": require("../../assets/font-awesome/svg/pagelines.svg"),
      "paint brush": require("../../assets/font-awesome/svg/paint-brush.svg"),
      "paper plane outline": require("../../assets/font-awesome/svg/paper-plane-o.svg"),
      "paper plane": require("../../assets/font-awesome/svg/paper-plane.svg"),
      "paperclip": require("../../assets/font-awesome/svg/paperclip.svg"),
      "paragraph": require("../../assets/font-awesome/svg/paragraph.svg"),
      "paste": require("../../assets/font-awesome/svg/paste.svg"),
      "pause circle outline": require("../../assets/font-awesome/svg/pause-circle-o.svg"),
      "pause circle": require("../../assets/font-awesome/svg/pause-circle.svg"),
      "pause": require("../../assets/font-awesome/svg/pause.svg"),
      "paw": require("../../assets/font-awesome/svg/paw.svg"),
      "paypal": require("../../assets/font-awesome/svg/paypal.svg"),
      "pencil square outline": require("../../assets/font-awesome/svg/pencil-square-o.svg"),
      "pencil square": require("../../assets/font-awesome/svg/pencil-square.svg"),
      "pencil": require("../../assets/font-awesome/svg/pencil.svg"),
      "percent": require("../../assets/font-awesome/svg/percent.svg"),
      "phone square": require("../../assets/font-awesome/svg/phone-square.svg"),
      "phone": require("../../assets/font-awesome/svg/phone.svg"),
      "photoutline": require("../../assets/font-awesome/svg/photo.svg"),
      "picture outline": require("../../assets/font-awesome/svg/picture-o.svg"),
      "pie chart": require("../../assets/font-awesome/svg/pie-chart.svg"),
      "pied piper alt": require("../../assets/font-awesome/svg/pied-piper-alt.svg"),
      "pied piper pp": require("../../assets/font-awesome/svg/pied-piper-pp.svg"),
      "pied piper": require("../../assets/font-awesome/svg/pied-piper.svg"),
      "pinterest p": require("../../assets/font-awesome/svg/pinterest-p.svg"),
      "pinterest square": require("../../assets/font-awesome/svg/pinterest-square.svg"),
      "pinterest": require("../../assets/font-awesome/svg/pinterest.svg"),
      "plane": require("../../assets/font-awesome/svg/plane.svg"),
      "play circle outline": require("../../assets/font-awesome/svg/play-circle-o.svg"),
      "play circle": require("../../assets/font-awesome/svg/play-circle.svg"),
      "play": require("../../assets/font-awesome/svg/play.svg"),
      "plug": require("../../assets/font-awesome/svg/plug.svg"),
      "plus circle": require("../../assets/font-awesome/svg/plus-circle.svg"),
      "plus square outline": require("../../assets/font-awesome/svg/plus-square-o.svg"),
      "plus square": require("../../assets/font-awesome/svg/plus-square.svg"),
      "plus": require("../../assets/font-awesome/svg/plus.svg"),
      "podcast": require("../../assets/font-awesome/svg/podcast.svg"),
      "power off": require("../../assets/font-awesome/svg/power-off.svg"),
      "print": require("../../assets/font-awesome/svg/print.svg"),
      "product hunt": require("../../assets/font-awesome/svg/product-hunt.svg"),
      "puzzle piece": require("../../assets/font-awesome/svg/puzzle-piece.svg"),
      "qq": require("../../assets/font-awesome/svg/qq.svg"),
      "qrcode": require("../../assets/font-awesome/svg/qrcode.svg"),
      "question circle outline": require("../../assets/font-awesome/svg/question-circle-o.svg"),
      "question circle": require("../../assets/font-awesome/svg/question-circle.svg"),
      "question": require("../../assets/font-awesome/svg/question.svg"),
      "quora": require("../../assets/font-awesome/svg/quora.svg"),
      "quote left": require("../../assets/font-awesome/svg/quote-left.svg"),
      "quote right": require("../../assets/font-awesome/svg/quote-right.svg"),
      "ra": require("../../assets/font-awesome/svg/ra.svg"),
      "random": require("../../assets/font-awesome/svg/random.svg"),
      "ravelry": require("../../assets/font-awesome/svg/ravelry.svg"),
      "rebel": require("../../assets/font-awesome/svg/rebel.svg"),
      "recycle": require("../../assets/font-awesome/svg/recycle.svg"),
      "reddit alien": require("../../assets/font-awesome/svg/reddit-alien.svg"),
      "reddit square": require("../../assets/font-awesome/svg/reddit-square.svg"),
      "reddit": require("../../assets/font-awesome/svg/reddit.svg"),
      "refresh": require("../../assets/font-awesome/svg/refresh.svg"),
      "registered": require("../../assets/font-awesome/svg/registered.svg"),
      "remove": require("../../assets/font-awesome/svg/remove.svg"),
      "renren": require("../../assets/font-awesome/svg/renren.svg"),
      "reorder": require("../../assets/font-awesome/svg/reorder.svg"),
      "repeat": require("../../assets/font-awesome/svg/repeat.svg"),
      "reply all": require("../../assets/font-awesome/svg/reply-all.svg"),
      "reply": require("../../assets/font-awesome/svg/reply.svg"),
      "resistance": require("../../assets/font-awesome/svg/resistance.svg"),
      "retweet": require("../../assets/font-awesome/svg/retweet.svg"),
      "rmb": require("../../assets/font-awesome/svg/rmb.svg"),
      "road": require("../../assets/font-awesome/svg/road.svg"),
      "rocket": require("../../assets/font-awesome/svg/rocket.svg"),
      "rotate left": require("../../assets/font-awesome/svg/rotate-left.svg"),
      "rotate right": require("../../assets/font-awesome/svg/rotate-right.svg"),
      "rouble": require("../../assets/font-awesome/svg/rouble.svg"),
      "rss square": require("../../assets/font-awesome/svg/rss-square.svg"),
      "rss": require("../../assets/font-awesome/svg/rss.svg"),
      "rub": require("../../assets/font-awesome/svg/rub.svg"),
      "ruble": require("../../assets/font-awesome/svg/ruble.svg"),
      "rupee": require("../../assets/font-awesome/svg/rupee.svg"),
      "s15": require("../../assets/font-awesome/svg/s15.svg"),
      "safari": require("../../assets/font-awesome/svg/safari.svg"),
      "save": require("../../assets/font-awesome/svg/save.svg"),
      "scissors": require("../../assets/font-awesome/svg/scissors.svg"),
      "scribd": require("../../assets/font-awesome/svg/scribd.svg"),
      "search minus": require("../../assets/font-awesome/svg/search-minus.svg"),
      "search plus": require("../../assets/font-awesome/svg/search-plus.svg"),
      "search": require("../../assets/font-awesome/svg/search.svg"),
      "sellsy": require("../../assets/font-awesome/svg/sellsy.svg"),
      "send outline": require("../../assets/font-awesome/svg/send-o.svg"),
      "send": require("../../assets/font-awesome/svg/send.svg"),
      "server": require("../../assets/font-awesome/svg/server.svg"),
      "share alt square": require("../../assets/font-awesome/svg/share-alt-square.svg"),
      "share alt": require("../../assets/font-awesome/svg/share-alt.svg"),
      "share square outline": require("../../assets/font-awesome/svg/share-square-o.svg"),
      "share square": require("../../assets/font-awesome/svg/share-square.svg"),
      "share": require("../../assets/font-awesome/svg/share.svg"),
      "shekel": require("../../assets/font-awesome/svg/shekel.svg"),
      "sheqel": require("../../assets/font-awesome/svg/sheqel.svg"),
      "shield": require("../../assets/font-awesome/svg/shield.svg"),
      "ship": require("../../assets/font-awesome/svg/ship.svg"),
      "shirtsinbulk": require("../../assets/font-awesome/svg/shirtsinbulk.svg"),
      "shopping bag": require("../../assets/font-awesome/svg/shopping-bag.svg"),
      "shopping basket": require("../../assets/font-awesome/svg/shopping-basket.svg"),
      "shopping cart": require("../../assets/font-awesome/svg/shopping-cart.svg"),
      "shower": require("../../assets/font-awesome/svg/shower.svg"),
      "sign in": require("../../assets/font-awesome/svg/sign-in.svg"),
      "sign language": require("../../assets/font-awesome/svg/sign-language.svg"),
      "sign out": require("../../assets/font-awesome/svg/sign-out.svg"),
      "signal": require("../../assets/font-awesome/svg/signal.svg"),
      "signing": require("../../assets/font-awesome/svg/signing.svg"),
      "simplybuilt": require("../../assets/font-awesome/svg/simplybuilt.svg"),
      "sitemap": require("../../assets/font-awesome/svg/sitemap.svg"),
      "skyatlas": require("../../assets/font-awesome/svg/skyatlas.svg"),
      "skype": require("../../assets/font-awesome/svg/skype.svg"),
      "slack": require("../../assets/font-awesome/svg/slack.svg"),
      "sliders": require("../../assets/font-awesome/svg/sliders.svg"),
      "slideshare": require("../../assets/font-awesome/svg/slideshare.svg"),
      "smile outline": require("../../assets/font-awesome/svg/smile-o.svg"),
      "snapchat ghost": require("../../assets/font-awesome/svg/snapchat-ghost.svg"),
      "snapchat square": require("../../assets/font-awesome/svg/snapchat-square.svg"),
      "snapchat": require("../../assets/font-awesome/svg/snapchat.svg"),
      "snowflake outline": require("../../assets/font-awesome/svg/snowflake-o.svg"),
      "soccer ball outline": require("../../assets/font-awesome/svg/soccer-ball-o.svg"),
      "sort alpha asc": require("../../assets/font-awesome/svg/sort-alpha-asc.svg"),
      "sort alpha desc": require("../../assets/font-awesome/svg/sort-alpha-desc.svg"),
      "sort amount asc": require("../../assets/font-awesome/svg/sort-amount-asc.svg"),
      "sort amount desc": require("../../assets/font-awesome/svg/sort-amount-desc.svg"),
      "sort asc": require("../../assets/font-awesome/svg/sort-asc.svg"),
      "sort desc": require("../../assets/font-awesome/svg/sort-desc.svg"),
      "sort down": require("../../assets/font-awesome/svg/sort-down.svg"),
      "sort numeric asc": require("../../assets/font-awesome/svg/sort-numeric-asc.svg"),
      "sort numeric desc": require("../../assets/font-awesome/svg/sort-numeric-desc.svg"),
      "sort up": require("../../assets/font-awesome/svg/sort-up.svg"),
      "sort": require("../../assets/font-awesome/svg/sort.svg"),
      "soundcloud": require("../../assets/font-awesome/svg/soundcloud.svg"),
      "space shuttle": require("../../assets/font-awesome/svg/space-shuttle.svg"),
      "spinner": require("../../assets/font-awesome/svg/spinner.svg"),
      "spoon": require("../../assets/font-awesome/svg/spoon.svg"),
      "spotify": require("../../assets/font-awesome/svg/spotify.svg"),
      "square outline": require("../../assets/font-awesome/svg/square-o.svg"),
      "square": require("../../assets/font-awesome/svg/square.svg"),
      "stack exchange": require("../../assets/font-awesome/svg/stack-exchange.svg"),
      "stack overflow": require("../../assets/font-awesome/svg/stack-overflow.svg"),
      "star half empty": require("../../assets/font-awesome/svg/star-half-empty.svg"),
      "star half full": require("../../assets/font-awesome/svg/star-half-full.svg"),
      "star half outline": require("../../assets/font-awesome/svg/star-half-o.svg"),
      "star half": require("../../assets/font-awesome/svg/star-half.svg"),
      "star outline": require("../../assets/font-awesome/svg/star-o.svg"),
      "star": require("../../assets/font-awesome/svg/star.svg"),
      "steam square": require("../../assets/font-awesome/svg/steam-square.svg"),
      "steam": require("../../assets/font-awesome/svg/steam.svg"),
      "step backward": require("../../assets/font-awesome/svg/step-backward.svg"),
      "step forward": require("../../assets/font-awesome/svg/step-forward.svg"),
      "stethoscope": require("../../assets/font-awesome/svg/stethoscope.svg"),
      "sticky note outline": require("../../assets/font-awesome/svg/sticky-note-o.svg"),
      "sticky note": require("../../assets/font-awesome/svg/sticky-note.svg"),
      "stop circle outline": require("../../assets/font-awesome/svg/stop-circle-o.svg"),
      "stop circle": require("../../assets/font-awesome/svg/stop-circle.svg"),
      "stop": require("../../assets/font-awesome/svg/stop.svg"),
      "street view": require("../../assets/font-awesome/svg/street-view.svg"),
      "strikethrough": require("../../assets/font-awesome/svg/strikethrough.svg"),
      "stumbleupon circle": require("../../assets/font-awesome/svg/stumbleupon-circle.svg"),
      "stumbleupon": require("../../assets/font-awesome/svg/stumbleupon.svg"),
      "subscript": require("../../assets/font-awesome/svg/subscript.svg"),
      "subway": require("../../assets/font-awesome/svg/subway.svg"),
      "suitcase": require("../../assets/font-awesome/svg/suitcase.svg"),
      "sun outline": require("../../assets/font-awesome/svg/sun-o.svg"),
      "superpowers": require("../../assets/font-awesome/svg/superpowers.svg"),
      "superscript": require("../../assets/font-awesome/svg/superscript.svg"),
      "support": require("../../assets/font-awesome/svg/support.svg"),
      "table": require("../../assets/font-awesome/svg/table.svg"),
      "tablet": require("../../assets/font-awesome/svg/tablet.svg"),
      "tachometer": require("../../assets/font-awesome/svg/tachometer.svg"),
      "tag": require("../../assets/font-awesome/svg/tag.svg"),
      "tags": require("../../assets/font-awesome/svg/tags.svg"),
      "tasks": require("../../assets/font-awesome/svg/tasks.svg"),
      "taxi": require("../../assets/font-awesome/svg/taxi.svg"),
      "telegram": require("../../assets/font-awesome/svg/telegram.svg"),
      "television": require("../../assets/font-awesome/svg/television.svg"),
      "tencent weiboutline": require("../../assets/font-awesome/svg/tencent-weibo.svg"),
      "terminal": require("../../assets/font-awesome/svg/terminal.svg"),
      "text height": require("../../assets/font-awesome/svg/text-height.svg"),
      "text width": require("../../assets/font-awesome/svg/text-width.svg"),
      "th large": require("../../assets/font-awesome/svg/th-large.svg"),
      "th list": require("../../assets/font-awesome/svg/th-list.svg"),
      "th": require("../../assets/font-awesome/svg/th.svg"),
      "themeisle": require("../../assets/font-awesome/svg/themeisle.svg"),
      "thermometer 0": require("../../assets/font-awesome/svg/thermometer-0.svg"),
      "thermometer 1": require("../../assets/font-awesome/svg/thermometer-1.svg"),
      "thermometer 2": require("../../assets/font-awesome/svg/thermometer-2.svg"),
      "thermometer 3": require("../../assets/font-awesome/svg/thermometer-3.svg"),
      "thermometer 4": require("../../assets/font-awesome/svg/thermometer-4.svg"),
      "thermometer empty": require("../../assets/font-awesome/svg/thermometer-empty.svg"),
      "thermometer full": require("../../assets/font-awesome/svg/thermometer-full.svg"),
      "thermometer half": require("../../assets/font-awesome/svg/thermometer-half.svg"),
      "thermometer quarter": require("../../assets/font-awesome/svg/thermometer-quarter.svg"),
      "thermometer three quarters": require("../../assets/font-awesome/svg/thermometer-three-quarters.svg"),
      "thermometer": require("../../assets/font-awesome/svg/thermometer.svg"),
      "thumb tack": require("../../assets/font-awesome/svg/thumb-tack.svg"),
      "thumbs down": require("../../assets/font-awesome/svg/thumbs-down.svg"),
      "thumbs o down": require("../../assets/font-awesome/svg/thumbs-o-down.svg"),
      "thumbs o up": require("../../assets/font-awesome/svg/thumbs-o-up.svg"),
      "thumbs up": require("../../assets/font-awesome/svg/thumbs-up.svg"),
      "ticket": require("../../assets/font-awesome/svg/ticket.svg"),
      "times circle outline": require("../../assets/font-awesome/svg/times-circle-o.svg"),
      "times circle": require("../../assets/font-awesome/svg/times-circle.svg"),
      "times rectangle outline": require("../../assets/font-awesome/svg/times-rectangle-o.svg"),
      "times rectangle": require("../../assets/font-awesome/svg/times-rectangle.svg"),
      "times": require("../../assets/font-awesome/svg/times.svg"),
      "tint": require("../../assets/font-awesome/svg/tint.svg"),
      "toggle down": require("../../assets/font-awesome/svg/toggle-down.svg"),
      "toggle left": require("../../assets/font-awesome/svg/toggle-left.svg"),
      "toggle off": require("../../assets/font-awesome/svg/toggle-off.svg"),
      "toggle on": require("../../assets/font-awesome/svg/toggle-on.svg"),
      "toggle right": require("../../assets/font-awesome/svg/toggle-right.svg"),
      "toggle up": require("../../assets/font-awesome/svg/toggle-up.svg"),
      "trademark": require("../../assets/font-awesome/svg/trademark.svg"),
      "train": require("../../assets/font-awesome/svg/train.svg"),
      "transgender alt": require("../../assets/font-awesome/svg/transgender-alt.svg"),
      "transgender": require("../../assets/font-awesome/svg/transgender.svg"),
      "trash outline": require("../../assets/font-awesome/svg/trash-o.svg"),
      "trash": require("../../assets/font-awesome/svg/trash.svg"),
      "tree": require("../../assets/font-awesome/svg/tree.svg"),
      "trelloutline": require("../../assets/font-awesome/svg/trello.svg"),
      "tripadvisor": require("../../assets/font-awesome/svg/tripadvisor.svg"),
      "trophy": require("../../assets/font-awesome/svg/trophy.svg"),
      "truck": require("../../assets/font-awesome/svg/truck.svg"),
      "try": require("../../assets/font-awesome/svg/try.svg"),
      "tty": require("../../assets/font-awesome/svg/tty.svg"),
      "tumblr square": require("../../assets/font-awesome/svg/tumblr-square.svg"),
      "tumblr": require("../../assets/font-awesome/svg/tumblr.svg"),
      "turkish lira": require("../../assets/font-awesome/svg/turkish-lira.svg"),
      "tv": require("../../assets/font-awesome/svg/tv.svg"),
      "twitch": require("../../assets/font-awesome/svg/twitch.svg"),
      "twitter square": require("../../assets/font-awesome/svg/twitter-square.svg"),
      "twitter": require("../../assets/font-awesome/svg/twitter.svg"),
      "umbrella": require("../../assets/font-awesome/svg/umbrella.svg"),
      "underline": require("../../assets/font-awesome/svg/underline.svg"),
      "undoutline": require("../../assets/font-awesome/svg/undo.svg"),
      "universal access": require("../../assets/font-awesome/svg/universal-access.svg"),
      "university": require("../../assets/font-awesome/svg/university.svg"),
      "unlink": require("../../assets/font-awesome/svg/unlink.svg"),
      "unlock alt": require("../../assets/font-awesome/svg/unlock-alt.svg"),
      "unlock": require("../../assets/font-awesome/svg/unlock.svg"),
      "unsorted": require("../../assets/font-awesome/svg/unsorted.svg"),
      "upload": require("../../assets/font-awesome/svg/upload.svg"),
      "usb": require("../../assets/font-awesome/svg/usb.svg"),
      "usd": require("../../assets/font-awesome/svg/usd.svg"),
      "user circle outline": require("../../assets/font-awesome/svg/user-circle-o.svg"),
      "user circle": require("../../assets/font-awesome/svg/user-circle.svg"),
      "user md": require("../../assets/font-awesome/svg/user-md.svg"),
      "user outline": require("../../assets/font-awesome/svg/user-o.svg"),
      "user plus": require("../../assets/font-awesome/svg/user-plus.svg"),
      "user secret": require("../../assets/font-awesome/svg/user-secret.svg"),
      "user times": require("../../assets/font-awesome/svg/user-times.svg"),
      "user": require("../../assets/font-awesome/svg/user.svg"),
      "users": require("../../assets/font-awesome/svg/users.svg"),
      "vcard outline": require("../../assets/font-awesome/svg/vcard-o.svg"),
      "vcard": require("../../assets/font-awesome/svg/vcard.svg"),
      "venus double": require("../../assets/font-awesome/svg/venus-double.svg"),
      "venus mars": require("../../assets/font-awesome/svg/venus-mars.svg"),
      "venus": require("../../assets/font-awesome/svg/venus.svg"),
      "viacoin": require("../../assets/font-awesome/svg/viacoin.svg"),
      "viadeo square": require("../../assets/font-awesome/svg/viadeo-square.svg"),
      "viadeoutline": require("../../assets/font-awesome/svg/viadeo.svg"),
      "video camera": require("../../assets/font-awesome/svg/video-camera.svg"),
      "vimeo square": require("../../assets/font-awesome/svg/vimeo-square.svg"),
      "vimeoutline": require("../../assets/font-awesome/svg/vimeo.svg"),
      "vine": require("../../assets/font-awesome/svg/vine.svg"),
      "vk": require("../../assets/font-awesome/svg/vk.svg"),
      "volume control phone": require("../../assets/font-awesome/svg/volume-control-phone.svg"),
      "volume down": require("../../assets/font-awesome/svg/volume-down.svg"),
      "volume off": require("../../assets/font-awesome/svg/volume-off.svg"),
      "volume up": require("../../assets/font-awesome/svg/volume-up.svg"),
      "warning": require("../../assets/font-awesome/svg/warning.svg"),
      "wechat": require("../../assets/font-awesome/svg/wechat.svg"),
      "weiboutline": require("../../assets/font-awesome/svg/weibo.svg"),
      "weixin": require("../../assets/font-awesome/svg/weixin.svg"),
      "whatsapp": require("../../assets/font-awesome/svg/whatsapp.svg"),
      "wheelchair alt": require("../../assets/font-awesome/svg/wheelchair-alt.svg"),
      "wheelchair": require("../../assets/font-awesome/svg/wheelchair.svg"),
      "wifi": require("../../assets/font-awesome/svg/wifi.svg"),
      "wikipedia w": require("../../assets/font-awesome/svg/wikipedia-w.svg"),
      "window close outline": require("../../assets/font-awesome/svg/window-close-o.svg"),
      "window close": require("../../assets/font-awesome/svg/window-close.svg"),
      "window maximize": require("../../assets/font-awesome/svg/window-maximize.svg"),
      "window minimize": require("../../assets/font-awesome/svg/window-minimize.svg"),
      "window restore": require("../../assets/font-awesome/svg/window-restore.svg"),
      "windows": require("../../assets/font-awesome/svg/windows.svg"),
      "won": require("../../assets/font-awesome/svg/won.svg"),
      "wordpress": require("../../assets/font-awesome/svg/wordpress.svg"),
      "wpbeginner": require("../../assets/font-awesome/svg/wpbeginner.svg"),
      "wpexplorer": require("../../assets/font-awesome/svg/wpexplorer.svg"),
      "wpforms": require("../../assets/font-awesome/svg/wpforms.svg"),
      "wrench": require("../../assets/font-awesome/svg/wrench.svg"),
      "xing square": require("../../assets/font-awesome/svg/xing-square.svg"),
      "xing": require("../../assets/font-awesome/svg/xing.svg"),
      "y combinator square": require("../../assets/font-awesome/svg/y-combinator-square.svg"),
      "y combinator": require("../../assets/font-awesome/svg/y-combinator.svg"),
      "yahooutline": require("../../assets/font-awesome/svg/yahoo.svg"),
      "yc square": require("../../assets/font-awesome/svg/yc-square.svg"),
      "yc": require("../../assets/font-awesome/svg/yc.svg"),
      "yelp": require("../../assets/font-awesome/svg/yelp.svg"),
      "yen": require("../../assets/font-awesome/svg/yen.svg"),
      "yoast": require("../../assets/font-awesome/svg/yoast.svg"),
      "youtube play": require("../../assets/font-awesome/svg/youtube-play.svg"),
      "youtube square": require("../../assets/font-awesome/svg/youtube-square.svg"),
      "youtube": require("../../assets/font-awesome/svg/youtube.svg"),
    }
  }
};
